### ISSUE TITLE
crash - stack included

### ISSUE THREAD

**Issue by darenr** [Jasonette/JASONETTE-Android#224]
it happens frequently but not with much predictability unfortunately

But reporting in case there's something here of use. Android 7.0

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 832932 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3812)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6237)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: android.os.TransactionTooLargeException: data parcel size 832932 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:618)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3664)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3804)
	... 7 more
```

**Comment by phyowaimg** [comment]
#224
