### ISSUE TITLE
Can't run demo app at Android 4.4.2 device

### ISSUE THREAD

**Issue by dreamadv** [Jasonette/JASONETTE-Android#256]
App crash after start:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.jasonette, PID: 6547
                  java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.jasonette-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.jasonette-2, /vendor/lib, /system/lib]]
                      at android.app.ActivityThread.installProvider(ActivityThread.java:5034)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4605)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4545)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:5315)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.jasonette-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.jasonette-2, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:5019)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4605) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4545) 
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402) 
                      at android.os.Handler.dispatchMessage(Handler.java:110) 
                      at android.os.Looper.loop(Looper.java:193) 
                      at android.app.ActivityThread.main(ActivityThread.java:5315) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by dreamadv** [comment]
Jason app from Play Marker also crash at startup.

**Comment by absjabed** [comment]
try running this one,
https://github.com/absjabed/jasonette-android-revised
I didn't knew it's development moved to [jasonelle](https://github.com/jasonelle/jasonelle) recently, so i had to reconfigure the app...

**Comment by clsource** [comment]
hello @absjabed I would love to merge your fixes in the jasonelle repo.
please contact me 👍 thanks. 

Also here is the Jason App APK if you need to test jsons with it 

https://github.com/jasonelle/jasonelle/releases 👍

**Comment by clsource** [comment]
As far as I Know, the minimum version for Android is 6.0 and for iOS is 9.0
because the libs used. Most new devices should have 6.0 (released in 2015) or newer so supporting 4.x is ancient by today standards. I am aware that there are lots of devices that still have 5.x or older SO, but I currently do not have the required knowledge or devices to test such configurations.

It's better that we consider "deprecated", devices below Android 6 and iOS 9 in order to keep the code base clean.

I'm closing this for now.
